#!/usr/bin/env bash
#
# Generator hook for the wasm test program. run-programs.sh runs this (by the
# conventional name generate.sh) before building, in the program's own
# directory.
#
# It compiles every Odin source under programs/ to a standalone
# freestanding-wasm32 module and embeds each one, as a byte-string constant,
# into generated.odin together with a run_generated() that drives every export
# of every module through the interpreter's generic all-exports path. Because
# the embedding happens once, up front, both the reference-Odin and JIT builds
# compile byte-identical source, so their outputs stay directly comparable.

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$DIR/programs"
OUT="$DIR/generated.odin"

# -o:none keeps the emitted body inside the small opcode subset the interpreter
# understands (no select-with-type, no bulk-memory, minimal folding); the
# bounds-check / assert guards are dropped so no runtime-panic imports appear.
FLAGS=(-target:freestanding_wasm32 -no-entry-point -no-bounds-check -disable-assert -o:none)

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

{
	echo "package main"
	echo
	echo "// GENERATED by generate.sh from the Odin sources under programs/ -- do not"
	echo "// edit by hand. Each constant is a freestanding-wasm32 build of the matching"
	echo "// .odin file, embedded as a byte string and executed through run_module_auto."
	echo
} >"$OUT"

names=()
for src in "$SRC"/*.odin; do
	name="$(basename "$src" .odin)"
	wasm="$tmp/$name.wasm"
	odin build "$src" -file "${FLAGS[@]}" -out:"$wasm" >/dev/null
	const="GEN_$(echo "$name" | tr '[:lower:]' '[:upper:]')"
	esc="$(od -An -v -tx1 "$wasm" | tr -d ' \n' | sed 's/../\\x&/g')"
	printf '%s :: "%s"\n\n' "$const" "$esc" >>"$OUT"
	names+=("$name|$const")
done

{
	echo "run_generated :: proc() -> int {"
	echo -e "\tacc := 0"
	for entry in "${names[@]}"; do
		n="${entry%%|*}"
		c="${entry##*|}"
		printf '\tacc += run_module_auto("%s", %s)\n' "$n" "$c"
	done
	echo -e "\treturn acc"
	echo "}"
} >>"$OUT"

echo "generated $OUT from ${#names[@]} module(s)"
